apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id + "-api"}}
  description: REST API for the service
spec:
  type: openapi
  lifecycle: experimental
  owner: cerberus-developers
  definition:
    $text: https://api.apis.guru/v2/specs/qualtrics.com/0.2/openapi.yaml
